const colors = {
  blue: 'blue',
  zero: 'zero',
  white: 'white',
  dark: 'dark',
  'dark-blue': 'dark-blue',
  'medium-blue': 'medium-blue',
  'dark-gray': 'dark-gray',
  'metal': 'metal',
  'gray': 'gray',
  'medium-gray': 'medium-gray',
  'light-gray': 'light-gray',
  'light': 'light',
  'lightness': 'lightness',
  'shine': 'shine',
  'red': 'red',
  'light-red': 'light-red',
  'yellow': 'yellow',
  'light-yellow': 'light-yellow',
  'green': 'green',
  'light-green': 'light-green',
  'violet': 'violet',
  'light-violet': 'light-violet',
  'light-blue': 'light-blue',
  transparent: 'transparent',
}

export default Object.freeze(colors)